import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations._();

  static String currentLanguage = 'en';

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'home': 'Home',
      'bookings': 'Bookings',
      'results': 'Results',
      'alerts': 'Alerts',
      'profile': 'Profile',
      'loading': 'Loading',
      'no_available_slots': 'No available slots for this day.',
      'location_map': 'CLINIC LOCATION',
      'welcome_title': 'Your trusted\ndoctor, one tap away.',
      'welcome_subtitle': 'Book specialists across Kirkuk — see verified doctors, transparent prices, same-day slots.',
      'feature_verified': 'Verified specialists only',
      'feature_private': 'Your records stay private',
      'feature_same_day': 'Same-day bookings available',
      'btn_start': 'Get started',
      'btn_login': 'I already have an account',
      'terms_agree': 'By continuing you agree to our Terms and Privacy Policy',
      'login_title': 'Log in',
      'login_subtitle': 'Log in to access your clinic and appointments.',
      'no_account': "Don't have an account? ",
      'register_link': 'Register',
      'account_not_found': 'Account Not Found',
      'account_not_found_desc': 'No account found with this number. Please register first.',
      'create_account': 'Create account',
      'lets_know_you': "Let's get to know you",
      'register_subtitle': 'We use your number to verify and remind you about appointments.',
      'full_name': 'Full name',
      'name_placeholder': 'e.g. Mustafa Ali',
      'phone_number': 'Phone number',
      'privacy_notice': 'Your number is only used for verification and appointment reminders. We never share it.',
      'continue_btn': 'Continue',
      'verify_number': 'Verify number',
      'check_messages': 'Check your messages',
      'otp_subtitle': 'We sent a 4-digit code to',
      'resend_code_in': 'Resend code in',
      'resend_code': 'Resend code',
      'demo_autofill': 'Demo: auto-fill code',
      'verify_continue': 'Verify & continue',
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'upcoming_appt': 'UPCOMING APPOINTMENT',
      'browse_specialty': 'Browse by specialty',
      'areas_count': '10 areas',
      'recommended_doctors': 'Recommended Doctors',
      'recommended_subtitle': 'Based on your history and top-rated specialists',
      'trust_title': 'Every doctor verified',
      'trust_sub': 'Licenses checked quarterly by our team',
      'my_bookings': 'My bookings',
      'tab_upcoming': 'Upcoming',
      'tab_past': 'Past',
      'no_appointments': 'No {{tab}} appointments yet.',
      'reschedule': 'Reschedule',
      'cancel': 'Cancel',
      'cancel_confirm_title': 'Cancel Appointment',
      'cancel_confirm_message': 'Are you sure you want to cancel this appointment?',
      'cancel_confirmed_warning': 'WARNING: You are cancelling a confirmed appointment. Frequent cancellations may lead to account restrictions. Proceed anyway?',
      'reschedule_denied_title': 'Cannot Reschedule',
      'reschedule_denied_message': 'Since your appointment is confirmed, you can no longer make changes. Please contact the clinic if needed.',
      'view_result': 'View result',
      'book_again': 'Book again',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'book_appointment': 'Book appointment',
      'choose_day': 'Choose day',
      'available_time': 'Available time',
      'legend_selected': 'Selected',
      'legend_available': 'Available',
      'legend_unavailable': 'Unavailable',
      'payment_method': 'Payment method',
      'pay_online': 'Pay online',
      'pay_online_sub': 'Visa, Mastercard, Zain Cash',
      'instant_confirm': 'Instant confirm',
      'pay_clinic': 'Pay at clinic',
      'pay_clinic_sub': 'Cash on arrival · pending confirm',
      'summary': 'SUMMARY',
      'consultation': 'Consultation',
      'service_fee': 'Service fee',
      'total': 'Total',
      'confirm_booking': 'Confirm booking',
      'processing': 'Processing...',
      'youre_booked': "You're booked!",
      'booking_confirmed_sub': 'We sent a confirmation to your phone. Please arrive 10 minutes early.',
      'ticket_date': 'DATE',
      'ticket_time': 'TIME',
      'ticket_location': 'LOCATION',
      'ticket_payment': 'PAYMENT',
      'paid_online': 'Paid online',
      'pay_at_clinic': 'Pay at clinic',
      'view_my_bookings': 'View my bookings',
      'back_to_home': 'Back to home',
      'profile_title': 'Profile',
      'visits': 'Visits',
      'your_rating': 'Your rating',
      'my_results': 'My results',
      'notifications': 'Notifications',
      'upcoming': 'upcoming',
      'reports': 'reports',
      'unread': 'unread',
      'help_center': 'Help center',
      'privacy': 'Privacy & security',
      'language': 'Language',
      'english': 'English',
      'turkish': 'Turkish',
      'arabic': 'Arabic',
      'kurdish': 'Kurdish',
      'logout': 'Log out',
      'edit_profile': 'Edit Profile',
      'edit_name': 'Your name',
      'save_changes': 'Save changes',
      'updating': 'Updating...',
      'notif_title': 'Notifications',
      'new_alerts': '{{count}} new alerts',
      'mark_all_read': 'Mark all read',
      'no_notifications': 'No Notifications',
      'no_notifications_sub': 'You have no new updates or appointment reminders.',
      'my_results_title': 'My results',
      'results_subtitle': 'Your full medical history in one place',
      'clinical_notes': 'CLINICAL NOTES',
      'medications': 'MEDICATIONS',
      'next_steps': 'NEXT STEPS',
      'all_doctors': 'All doctors',
      'available_today': 'Available today',
      'top_rated': 'Top rated',
      'nearby': 'Nearby',
      'doctors_count': '{{count}} doctors',
      'doctor_title': 'Doctor',
      'experience_suffix': 'experience',
      'about': 'ABOUT',
      'about_text': 'Specialist with over {{exp}} of clinical practice. Member of the Iraqi Dental Association. Focus on modern, pain-minimizing approaches and patient education.',
      'working_hours': 'WORKING HOURS',
      'hours_sat_thu': 'Sat – Thu',
      'hours_fri': 'Friday',
      'hours_closed': 'Closed',
      'next_available': 'NEXT AVAILABLE',
      'see_all': 'See all',
      'today_badge': 'Today',
      'consultation_label': 'CONSULTATION',
      'book_appointment_btn': 'Book appointment',
      'help_center_title': 'Help center',
      'new_ticket': 'NEW COMPLAINT',
      'category': 'Category',
      'cat_booking': 'Booking',
      'cat_payment': 'Payment',
      'cat_results': 'Results',
      'cat_other': 'Other',
      'subject_placeholder': 'Subject',
      'message_placeholder': 'Describe your issue...',
      'submit_ticket': 'Submit complaint',
      'ticket_submitted': '✓ Complaint submitted',
      'your_tickets': 'YOUR COMPLAINTS',
      'status_confirmed': 'Confirmed',
      'status_pending': 'Pending',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      'status_open': 'Open',
      'status_resolved': 'Resolved',
      'privacy_title': 'Privacy & security',
      'data_protection': 'DATA PROTECTION',
      'data_protection_desc': 'Your medical records and personal data are encrypted and stored securely in compliance with healthcare standards.',
      'account_security': 'ACCOUNT SECURITY',
      'change_phone': 'Change phone number',
      'delete_account': 'Delete account',
      'delete_warning': 'This action is permanent and will delete all your medical history.',
      'permissions': 'PERMISSIONS',
      'notif_perms': 'Notification permissions',
      'loc_perms': 'Location permissions',
      'error': 'Error',
      'rating_save_error': 'Could not save rating: ',
      'thanks': 'Thanks',
      'rating_success': 'Your rating was submitted successfully!',
      'something_went_wrong': 'Something went wrong: ',
      'unknown_doctor': 'Unknown Doctor',
      'rate_doctor_title': 'Rate Doctor',
      'rate_doctor_sub': 'Rate your appointment with {{doctor}}.',
      'rate_doctor_placeholder': 'Write your comments about the doctor and examination (optional)...',
      'cancel_btn_text': 'Cancel',
      'submit_btn_text': 'Submit',
      'saving': 'Saving...',
      'rated_x_out_of_5': '⭐ Rated {{rating}} / 5',
      'rate_btn': '⭐ Rate',
      'day_mon': 'Monday',
      'day_tue': 'Tuesday',
      'day_wed': 'Wednesday',
      'day_thu': 'Thursday',
      'day_fri': 'Friday',
      'day_sat': 'Saturday',
      'day_sun': 'Sunday',
      'view_on_maps': 'View on Google Maps',
      'no_location_info': 'No location information available.',
      'reports_available': '{{count}} reports available',
      'no_reports_yet': 'No uploaded reports yet.',
      'ai_summary': 'AI Summary',
      'summary_not_ready': 'Summary not generated yet.',
      'view_report_pdf': 'View Report (PDF)',
      'downloading': 'Downloading...',
      'sharing_not_available': 'Sharing is not available on this device.',
      'pdf_download_error': 'Could not download PDF. Please try again.',
      'no_report_available': 'Medical examination completed. No report available.',
      'complaint_failed': 'Failed to submit complaint.',
      'no_complaints_yet': 'You have no complaints yet.',
      'faq_q1': 'How can I book an appointment?',
      'faq_a1': 'You can easily book an appointment by selecting the desired specialty from the home page, choosing your doctor, and setting an available time.',
      'faq_q2:': 'Can I cancel my appointment?',
      'faq_a2': 'You can freely cancel unconfirmed appointments. However, frequent cancellations of confirmed appointments may result in a temporary block of your account.',
      'faq_q3': 'Where can I see my results?',
      'faq_a3': 'You can access all your past medical reports and AI summaries from the "My Results" tab.',
      'faq_q4': 'How is the payment made?',
      'faq_a4': 'We offer both online (card or Zain Cash) and in-clinic cash payment options.',
      'submit_complaint_title': 'Contact Us / Submit Complaint',
      'submit_complaint_sub': 'Send your issues directly to us.',
      'faqs': 'FREQUENTLY ASKED QUESTIONS',
      'about_us_label': 'ABOUT US',
      'about_us_text': 'Tabeebi+ is a modern health platform that provides easy access to specialist doctors across Kirkuk. Our goal is to accelerate healthcare processes by digitizing communication between patients and doctors.',
      'complaint_success_msg': 'Your complaint has been submitted successfully. We will review it and get back to you as soon as possible.',
      'ai_health_assistant': 'AI Health Assistant',
      'ai_companion': 'Your personal health companion. Ask anything, anytime.',
      'ask_ai_btn': 'Ask AI',
      'ai_tab': 'AI',
      'ai_chat_title': 'AI Health Assistant',
      'ai_chat_sub': 'Powered by Tabeebi+',
      'ai_empty_title': 'How can I help you?',
      'ai_empty_sub': 'Ask me anything about your health, symptoms or medications.',
      'ai_suggestion_1': 'What are common symptoms of flu?',
      'ai_suggestion_2': 'When should I see a doctor for a headache?',
      'ai_suggestion_3': 'How can I lower my blood pressure naturally?',
      'ai_input_placeholder': 'Ask a health question...',
      'ai_placeholder_response': 'This is a demo response. Full AI integration coming soon!',
    },
    'tr': {
      'home': 'Ana Sayfa',
      'bookings': 'Randevular',
      'results': 'Sonuçlar',
      'alerts': 'Bildirimler',
      'profile': 'Profil',
      'loading': 'Yükleniyor',
      'no_available_slots': 'Bu gün için müsait randevu saati bulunmuyor.',
      'location_map': 'KLİNİK KONUMU',
      'welcome_title': 'Güvenilir doktorunuz\nbir tık uzağınızda.',
      'welcome_subtitle': 'Kerkük genelindeki uzmanlardan randevu alın — onaylı doktorlar, şeffaf fiyatlar, aynı gün randevu.',
      'feature_verified': 'Sadece onaylı uzmanlar',
      'feature_private': 'Kayıtlarınız gizli tutulur',
      'feature_same_day': 'Aynı gün randevu imkânı',
      'btn_start': 'Hemen başla',
      'btn_login': 'Zaten hesabım var',
      'terms_agree': 'Devam ederek Kullanım Şartları ve Gizlilik Politikasını kabul etmiş olursunuz',
      'login_title': 'Giriş Yap',
      'login_subtitle': 'Kliniğinize ve randevularınıza ulaşmak için giriş yapın.',
      'no_account': 'Hesabınız yok mu? ',
      'register_link': 'Kayıt Ol',
      'account_not_found': 'Hesap Bulunamadı',
      'account_not_found_desc': 'Bu numara ile kayıtlı hesap bulunamadı. Lütfen önce kayıt olun.',
      'create_account': 'Hesap oluştur',
      'lets_know_you': 'Sizi tanıyalım',
      'register_subtitle': 'Numaranızı doğrulama ve randevu hatırlatmaları için kullanıyoruz.',
      'full_name': 'Ad Soyad',
      'name_placeholder': 'örn. Mustafa Ali',
      'phone_number': 'Telefon numarası',
      'privacy_notice': 'Numaranız yalnızca doğrulama ve randevu hatırlatmaları için kullanılır. Asla paylaşmayız.',
      'continue_btn': 'Devam et',
      'verify_number': 'Numarayı doğrula',
      'check_messages': 'Mesajlarınızı kontrol edin',
      'otp_subtitle': '4 haneli kodu şu numaraya gönderdik:',
      'resend_code_in': 'Kodu tekrar gönder:',
      'resend_code': 'Kodu tekrar gönder',
      'demo_autofill': 'Demo: kodu otomatik doldur',
      'verify_continue': 'Doğrula ve devam et',
      'good_morning': 'Günaydın',
      'good_afternoon': 'Tünaydın',
      'good_evening': 'İyi akşamlar',
      'upcoming_appt': 'YAKLAŞAN RANDEVU',
      'browse_specialty': 'Uzmanlığa göre ara',
      'areas_count': '10 alan',
      'recommended_doctors': 'Sizin İçin Önerilen Hekimler',
      'recommended_subtitle': 'Muayene geçmişinize ve en yüksek puanlı uzmanlara göre',
      'trust_title': 'Her doktor onaylıdır',
      'trust_sub': 'Lisanslar ekibimiz tarafından üç ayda bir kontrol edilir',
      'my_bookings': 'Randevularım',
      'tab_upcoming': 'Yaklaşan',
      'tab_past': 'Geçmiş',
      'no_appointments': 'Henüz {{tab}} randevunuz yok.',
      'reschedule': 'Yeniden planla',
      'cancel': 'İptal et',
      'cancel_confirm_title': 'Randevuyu İptal Et',
      'cancel_confirm_message': 'Bu randevuyu iptal etmek istediğinize emin misiniz?',
      'cancel_confirmed_warning': 'UYARI: Onaylanmış bir randevuyu iptal ediyorsunuz. Sık yapılan iptaller hesabınızın kısıtlanmasına neden olabilir. Yine de iptal edilsin mi?',
      'reschedule_denied_title': 'Değişiklik Yapılamaz',
      'reschedule_denied_message': 'Randevunuz onaylandığı için artık üzerinde değişiklik yapamazsınız. Lütfen gerekirse klinikle iletişime geçin.',
      'view_result': 'Sonucu gör',
      'book_again': 'Tekrar randevu al',
      'yes': 'Evet',
      'no': 'Hayır',
      'ok': 'Tamam',
      'book_appointment': 'Randevu al',
      'choose_day': 'Gün seç',
      'available_time': 'Müsait saatler',
      'legend_selected': 'Seçili',
      'legend_available': 'Müsait',
      'legend_unavailable': 'Dolu',
      'payment_method': 'Ödeme yöntemi',
      'pay_online': 'Online öde',
      'pay_online_sub': 'Visa, Mastercard, Zain Cash',
      'instant_confirm': 'Anında onay',
      'pay_clinic': 'Klinikte öde',
      'pay_clinic_sub': 'Gelişte nakit · onay bekliyor',
      'summary': 'ÖZET',
      'consultation': 'Muayene',
      'service_fee': 'Hizmet ücreti',
      'total': 'Toplam',
      'confirm_booking': 'Randevuyu onayla',
      'processing': 'İşleniyor...',
      'youre_booked': 'Randevunuz alındı!',
      'booking_confirmed_sub': 'Telefonunuza onay gönderdik. Lütfen 10 dakika erken gelin.',
      'ticket_date': 'TARİH',
      'ticket_time': 'SAAT',
      'ticket_location': 'KONUM',
      'ticket_payment': 'ÖDEME',
      'paid_online': 'Online ödendi',
      'pay_at_clinic': 'Klinikte öde',
      'view_my_bookings': 'Randevularımı gör',
      'back_to_home': 'Ana sayfaya dön',
      'profile_title': 'Profil',
      'visits': 'Ziyaretler',
      'your_rating': 'Puanınız',
      'my_results': 'Sonuçlarım',
      'notifications': 'Bildirimler',
      'upcoming': 'yaklaşan',
      'reports': 'rapor',
      'unread': 'okunmamış',
      'help_center': 'Yardım merkezi',
      'privacy': 'Gizlilik ve güvenlik',
      'language': 'Dil',
      'english': 'İngilizce',
      'turkish': 'Türkçe',
      'arabic': 'Arapça',
      'kurdish': 'Kürtçe',
      'logout': 'Çıkış yap',
      'edit_profile': 'Profili Düzenle',
      'edit_name': 'Adınız Soyadınız',
      'save_changes': 'Değişiklikleri kaydet',
      'updating': 'Güncelleniyor...',
      'notif_title': 'Bildirimler',
      'new_alerts': '{{count}} yeni bildirim',
      'mark_all_read': 'Tümünü okundu işaretle',
      'no_notifications': 'Bildirim Bulunmuyor',
      'no_notifications_sub': 'Herhangi bir yeni güncelleme veya randevu uyarınız yok.',
      'my_results_title': 'Sonuçlarım',
      'results_subtitle': 'Tüm tıbbi geçmişiniz tek bir yerde',
      'clinical_notes': 'KLİNİK NOTLAR',
      'medications': 'İLAÇLAR',
      'next_steps': 'SONRAKİ ADIMLAR',
      'all_doctors': 'Tüm doktorlar',
      'available_today': 'Bugün müsait',
      'top_rated': 'En yüksek puanlı',
      'nearby': 'Yakınımdakiler',
      'doctors_count': '{{count}} doktor',
      'doctor_title': 'Doktor',
      'experience_suffix': 'deneyim',
      'about': 'HAKKINDA',
      'about_text': '{{exp}} klinik deneyime sahip uzman. Irak Diş Hekimleri Birliği üyesi. Modern, ağrı minimize eden yaklaşımlar ve hasta eğitimine odaklanır.',
      'working_hours': 'ÇALIŞMA SAATLERİ',
      'hours_sat_thu': 'Cmt – Per',
      'hours_fri': 'Cuma',
      'hours_closed': 'Kapalı',
      'next_available': 'SONRAKİ MÜSAIT',
      'see_all': 'Tümünü gör',
      'today_badge': 'Bugün',
      'consultation_label': 'MUAYENE',
      'book_appointment_btn': 'Randevu al',
      'help_center_title': 'Yardım merkezi',
      'new_ticket': 'YENİ ŞİKAYET',
      'category': 'Kategori',
      'cat_booking': 'Randevu',
      'cat_payment': 'Ödeme',
      'cat_results': 'Sonuçlar',
      'cat_other': 'Diğer',
      'subject_placeholder': 'Konu',
      'message_placeholder': 'Şikayetinizi açıklayın...',
      'submit_ticket': 'Şikayeti gönder',
      'ticket_submitted': '✓ Şikayet gönderildi',
      'your_tickets': 'ŞİKAYETLERİNİZ',
      'status_confirmed': 'Onaylandı',
      'status_pending': 'Beklemede',
      'status_completed': 'Tamamlandı',
      'status_cancelled': 'İptal edildi',
      'status_open': 'Açık',
      'status_resolved': 'Çözüldü',
      'privacy_title': 'Gizlilik ve güvenlik',
      'data_protection': 'VERİ KORUMASI',
      'data_protection_desc': 'Tıbbi kayıtlarınız ve kişisel verileriniz şifrelenir ve sağlık standartlarına uygun olarak güvenli bir şekilde saklanır.',
      'account_security': 'HESAP GÜVENLİĞİ',
      'change_phone': 'Telefon numarasını değiştir',
      'delete_account': 'Hesabı sil',
      'delete_warning': 'Bu işlem kalıcıdır ve tüm tıbbi geçmişinizi silecektir.',
      'permissions': 'İZİNLER',
      'notif_perms': 'Bildirim izinleri',
      'loc_perms': 'Konum izinleri',
      'error': 'Hata',
      'rating_save_error': 'Değerlendirme kaydedilemedi: ',
      'thanks': 'Teşekkürler',
      'rating_success': 'Değerlendirmeniz başarıyla iletildi!',
      'something_went_wrong': 'Bir sorun oluştu: ',
      'unknown_doctor': 'Bilinmeyen Doktor',
      'rate_doctor_title': 'Doktoru Değerlendir',
      'rate_doctor_sub': '{{doctor}} ile olan randevunuzu puanlayın.',
      'rate_doctor_placeholder': 'Doktor ve muayene hakkında yorumunuzu yazın (isteğe bağlı)...',
      'cancel_btn_text': 'Vazgeç',
      'submit_btn_text': 'Gönder',
      'saving': 'Kaydediliyor...',
      'rated_x_out_of_5': '⭐ {{rating}} / 5 Puan Verildi',
      'rate_btn': '⭐ Puan Ver',
      'day_mon': 'Pazartesi',
      'day_tue': 'Salı',
      'day_wed': 'Çarşamba',
      'day_thu': 'Perşembe',
      'day_fri': 'Cuma',
      'day_sat': 'Cumartesi',
      'day_sun': 'Pazar',
      'view_on_maps': 'Google Maps\'te görüntüle',
      'no_location_info': 'Konum bilgisi bulunmuyor.',
      'reports_available': '{{count}} rapor mevcut',
      'no_reports_yet': 'Henüz yüklenmiş rapor yok.',
      'ai_summary': 'AI Özeti',
      'summary_not_ready': 'Özet henüz oluşturulmadı.',
      'view_report_pdf': 'Raporu Görüntüle (PDF)',
      'downloading': 'İndiriliyor...',
      'sharing_not_available': 'Bu cihazda paylaşım desteklenmiyor.',
      'pdf_download_error': 'PDF indirilemedi. Lütfen tekrar deneyin.',
      'no_report_available': 'Muayene yapıldı. Rapor bulunmamaktadır.',
      'complaint_failed': 'Şikayet gönderilemedi.',
      'no_complaints_yet': 'Henüz bir şikayetiniz yok.',
      'faq_q1': 'Nasıl randevu alabilirim?',
      'faq_a1': 'Ana sayfadan istediğiniz uzmanlık alanını seçip, doktorunuzu ve uygun saati belirleyerek randevunuzu kolayca oluşturabilirsiniz.',
      'faq_q2': 'Randevumu iptal edebilir miyim?',
      'faq_a2': 'Onaylanmamış randevuları serbestçe iptal edebilirsiniz. Ancak onaylanmış randevuların sık iptal edilmesi durumunda hesabınız geçici olarak bloklanabilir.',
      'faq_q3': 'Sonuçlarımı nerede görebilirim?',
      'faq_a3': '"Sonuçlarım" sekmesinden tüm geçmiş tıbbi raporlarınıza ve AI özetlerinize ulaşabilirsiniz.',
      'faq_q4': 'Ödeme nasıl yapılır?',
      'faq_a4': 'Hem online (kart veya Zain Cash) hem de klinikte nakit ödeme seçeneklerimiz mevcuttur.',
      'submit_complaint_title': 'Bize Ulaşın / Şikayet Bildir',
      'submit_complaint_sub': 'Sorunlarınızı doğrudan bize iletin.',
      'faqs': 'SIKÇA SORULAN SORULAR',
      'about_us_label': 'BİZ KİMİZ',
      'about_us_text': 'Tabeebi+, Kerkük genelinde uzman doktorlara kolayca ulaşmanızı sağlayan modern bir sağlık platformudur. Amacımız, hasta ve doktor arasındaki iletişimi dijitalleştirerek sağlık süreçlerini hızlandırmaktır.',
      'complaint_success_msg': 'Şikayetiniz başarıyla iletildi. En kısa sürede inceleyip size dönüş yapacağız.',
      'ai_health_assistant': 'AI Sağlık Asistanı',
      'ai_companion': 'Kişisel sağlık yardımcınız. İstediğiniz zaman sorun.',
      'ask_ai_btn': "AI'a Sor",
      'ai_tab': 'AI',
      'ai_chat_title': 'AI Sağlık Asistanı',
      'ai_chat_sub': 'Tabeebi+ tarafından desteklenmektedir',
      'ai_empty_title': 'Size nasıl yardımcı olabilirim?',
      'ai_empty_sub': 'Sağlığınız, belirtileriniz veya ilaçlar hakkında her şeyi sorabilirsiniz.',
      'ai_suggestion_1': 'Grip belirtileri nelerdir?',
      'ai_suggestion_2': 'Baş ağrısında doktora ne zaman gitmeliyim?',
      'ai_suggestion_3': 'Tanşiyonımu doğal yollarla nasıl düşürebilirim?',
      'ai_input_placeholder': 'Sağlık sorusu sorun...',
      'ai_placeholder_response': 'Bu bir demo yanıtıdır. Tam AI entegrasyonu yakında geliyor!',
    },
    'ar': {
      'home': 'الرئيسية',
      'bookings': 'مواعيدي',
      'results': 'النتائج',
      'alerts': 'الإشعارات',
      'profile': 'الملف الشخصي',
      'loading': 'جارٍ التحميل',
      'no_available_slots': 'لا توجد مواعيد متاحة لهذا اليوم.',
      'location_map': 'موقع العيادة',
      'welcome_title': 'طبيبك الموثوق،\nبضغطة واحدة.',
      'welcome_subtitle': 'احجز مع أفضل الأطباء في كركوك — أطباء معتمدون، أسعار شفافة، مواعيد في نفس اليوم.',
      'feature_verified': 'أطباء معتمدون فقط',
      'feature_private': 'سجلاتك تبقى خاصة',
      'feature_same_day': 'مواعيد متاحة في نفس اليوم',
      'btn_start': 'ابدأ الآن',
      'btn_login': 'لدي حساب بالفعل',
      'terms_agree': 'بالمتابعة، أنت توافق على الشروط وسياسة الخصوصية',
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'تسجيل الدخول للوصول إلى عيادتك ومواعيدك.',
      'no_account': 'ليس لديك حساب؟ ',
      'register_link': 'تسجيل',
      'account_not_found': 'الحساب غير موجود',
      'account_not_found_desc': 'لم يتم العثور على حساب بهذا الرقم. يرجى التسجيل أولاً.',
      'create_account': 'إنشاء حساب',
      'lets_know_you': 'دعنا نتعرف عليك',
      'register_subtitle': 'نستخدم رقمك للتحقق وتذكيرك بمواعيدك.',
      'full_name': 'الاسم الكامل',
      'name_placeholder': 'مثال: مصطفى علي',
      'phone_number': 'رقم الهاتف',
      'privacy_notice': 'يُستخدم رقمك فقط للتحقق وتذكيرات المواعيد. لن نشاركه مطلقاً.',
      'continue_btn': 'متابعة',
      'verify_number': 'تحقّق من الرقم',
      'check_messages': 'تحقق من رسائلك',
      'otp_subtitle': 'أرسلنا رمزاً مكوناً من 4 أرقام إلى',
      'resend_code_in': 'إعادة الإرسال خلال',
      'resend_code': 'إعادة إرسال الرمز',
      'demo_autofill': 'تجريبي: ملء الرمز تلقائياً',
      'verify_continue': 'تحقق وتابع',
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء النور',
      'upcoming_appt': 'الموعد القادم',
      'browse_specialty': 'تصفح حسب التخصص',
      'areas_count': '١٠ تخصصات',
      'recommended_doctors': 'أطباء مقترحون لك',
      'recommended_subtitle': 'بناءً على سجلك وأعلى الأطباء تقييماً',
      'trust_title': 'كل طبيب معتمد',
      'trust_sub': 'يتم فحص التراخيص ربع سنوياً من قِبل فريقنا',
      'my_bookings': 'مواعيدي',
      'tab_upcoming': 'القادمة',
      'tab_past': 'السابقة',
      'no_appointments': 'لا توجد مواعيد {{tab}} حتى الآن.',
      'reschedule': 'إعادة الجدولة',
      'cancel': 'إلغاء',
      'cancel_confirm_title': 'إلغاء الموعد',
      'cancel_confirm_message': 'هل أنت متأكد من إلغاء هذا الموعد؟',
      'cancel_confirmed_warning': 'تحذير: أنت تلغي موعداً مؤكداً. قد تؤدي الإلغاءات المتكررة إلى تقييد حسابك. هل تريد المتابعة؟',
      'reschedule_denied_title': 'لا يمكن إعادة الجدولة',
      'reschedule_denied_message': 'بما أن موعدك مؤكد، لم يعد بإمكانك إجراء تغييرات. يرجى التواصل مع العيادة إذا لزم الأمر.',
      'view_result': 'عرض النتيجة',
      'book_again': 'حجز مرة أخرى',
      'yes': 'نعم',
      'no': 'لا',
      'ok': 'حسناً',
      'book_appointment': 'حجز موعد',
      'choose_day': 'اختر اليوم',
      'available_time': 'الأوقات المتاحة',
      'legend_selected': 'محدد',
      'legend_available': 'متاح',
      'legend_unavailable': 'محجوز',
      'payment_method': 'طريقة الدفع',
      'pay_online': 'الدفع الإلكتروني',
      'pay_online_sub': 'Visa, Mastercard, Zain Cash',
      'instant_confirm': 'تأكيد فوري',
      'pay_clinic': 'الدفع في العيادة',
      'pay_clinic_sub': 'نقداً عند الحضور · في انتظار التأكيد',
      'summary': 'الملخص',
      'consultation': 'الاستشارة',
      'service_fee': 'رسوم الخدمة',
      'total': 'المجموع',
      'confirm_booking': 'تأكيد الحجز',
      'processing': 'جارٍ المعالجة...',
      'youre_booked': 'تم الحجز!',
      'booking_confirmed_sub': 'أرسلنا تأكيداً إلى هاتفك. يرجى الحضور قبل ١٠ دقائق.',
      'ticket_date': 'التاريخ',
      'ticket_time': 'الوقت',
      'ticket_location': 'الموقع',
      'ticket_payment': 'الدفع',
      'paid_online': 'تم الدفع إلكترونياً',
      'pay_at_clinic': 'الدفع في العيادة',
      'view_my_bookings': 'عرض مواعيدي',
      'back_to_home': 'العودة إلى الرئيسية',
      'profile_title': 'الملف الشخصي',
      'visits': 'الزيارات',
      'your_rating': 'تقييمك',
      'my_results': 'نتائجي',
      'notifications': 'الإشعارات',
      'upcoming': 'قادم',
      'reports': 'تقرير',
      'unread': 'غير مقروء',
      'help_center': 'مركز المساعدة',
      'privacy': 'الخصوصية والأمان',
      'language': 'اللغة',
      'english': 'الإنجليزية',
      'turkish': 'التركية',
      'arabic': 'العربية',
      'kurdish': 'الكردية',
      'logout': 'تسجيل الخروج',
      'edit_profile': 'تعديل الملف الشخصي',
      'edit_name': 'اسمك',
      'save_changes': 'حفظ التغييرات',
      'updating': 'جارٍ التحديث...',
      'notif_title': 'الإشعارات',
      'new_alerts': '{{count}} إشعارات جديدة',
      'mark_all_read': 'تعليم الكل كمقروء',
      'no_notifications': 'لا توجد إشعارات',
      'no_notifications_sub': 'لا توجد تحديثات جديدة أو تذكيرات مواعيد.',
      'my_results_title': 'نتائجي',
      'results_subtitle': 'سجلك الطبي الكامل في مكان واحد',
      'clinical_notes': 'الملاحظات السريرية',
      'medications': 'الأدوية',
      'next_steps': 'الخطوات القادمة',
      'all_doctors': 'جميع الأطباء',
      'available_today': 'متاح اليوم',
      'top_rated': 'الأعلى تقييماً',
      'nearby': 'القريبون مني',
      'doctors_count': '{{count}} طبيب',
      'doctor_title': 'طبيب',
      'experience_suffix': 'خبرة',
      'about': 'نبذة عن الطبيب',
      'about_text': 'متخصص بأكثر من {{exp}} من الممارسة السريرية. عضو في نقابة أطباء الأسنان العراقية. يركز على الأساليب الحديثة وتقليل الألم وتثقيف المريض.',
      'working_hours': 'ساعات العمل',
      'hours_sat_thu': 'السبت – الخميس',
      'hours_fri': 'الجمعة',
      'hours_closed': 'مغلق',
      'next_available': 'أقرب موعد متاح',
      'see_all': 'عرض الكل',
      'today_badge': 'اليوم',
      'consultation_label': 'الاستشارة',
      'book_appointment_btn': 'حجز موعد',
      'help_center_title': 'مركز المساعدة',
      'new_ticket': 'شكوى جديدة',
      'category': 'الفئة',
      'cat_booking': 'الحجز',
      'cat_payment': 'الدفع',
      'cat_results': 'النتائج',
      'cat_other': 'أخرى',
      'subject_placeholder': 'الموضوع',
      'message_placeholder': 'اشرح مشكلتك...',
      'submit_ticket': 'إرسال الشكوى',
      'ticket_submitted': '✓ تم إرسال الشكوى',
      'your_tickets': 'شكاواك',
      'status_confirmed': 'مؤكد',
      'status_pending': 'قيد الانتظار',
      'status_completed': 'مكتمل',
      'status_cancelled': 'ملغى',
      'status_open': 'مفتوح',
      'status_resolved': 'تم الحل',
      'privacy_title': 'الخصوصية والأمان',
      'data_protection': 'حماية البيانات',
      'data_protection_desc': 'سجلاتك الطبية وبياناتك الشخصية مشفرة ومخزنة بشكل آمن وفقاً لمعايير الرعاية الصحية.',
      'account_security': 'أمان الحساب',
      'change_phone': 'تغيير رقم الهاتف',
      'delete_account': 'حذف الحساب',
      'delete_warning': 'هذا الإجراء دائم وسيحذف كامل سجلك الطبي.',
      'permissions': 'الأذونات',
      'notif_perms': 'أذونات الإشعارات',
      'loc_perms': 'أذونات الموقع',
      'error': 'خطأ',
      'rating_save_error': 'تعذر حفظ التقييم: ',
      'thanks': 'شكرًا لك',
      'rating_success': 'تم إرسال تقييمك بنجاح!',
      'something_went_wrong': 'حدث خطأ ما: ',
      'unknown_doctor': 'طبيب غير معروف',
      'rate_doctor_title': 'تقييم الطبيب',
      'rate_doctor_sub': 'قيّم موعدك مع {{doctor}}.',
      'rate_doctor_placeholder': 'اكتب تعليقاتك حول الطبيب والفحص (اختياري)...',
      'cancel_btn_text': 'إلغاء',
      'submit_btn_text': 'إرسال',
      'saving': 'جارٍ الحفظ...',
      'rated_x_out_of_5': '⭐ تم التقييم {{rating}} / 5',
      'rate_btn': '⭐ تقييم',
      'day_mon': 'الاثنين',
      'day_tue': 'الثلاثاء',
      'day_wed': 'الأربعاء',
      'day_thu': 'الخميس',
      'day_fri': 'الجمعة',
      'day_sat': 'السبت',
      'day_sun': 'الأحد',
      'view_on_maps': 'عرض على خرائط جوجل',
      'no_location_info': 'لا تتوفر معلومات عن الموقع.',
      'reports_available': '{{count}} تقارير متاحة',
      'no_reports_yet': 'لا توجد تقارير مرفوعة بعد.',
      'ai_summary': 'ملخص الذكاء الاصطناعي',
      'summary_not_ready': 'لم يتم إنشاء الملخص بعد.',
      'view_report_pdf': 'عرض التقرير (PDF)',
      'downloading': 'جاري التحميل...',
      'sharing_not_available': 'المشاركة غير متاحة على هذا الجهاز.',
      'pdf_download_error': 'تعذر تحميل ملف PDF. يرجى المحاولة مرة أخرى.',
      'no_report_available': 'تم إجراء الفحص الطبي. لا يوجد تقرير متاح.',
      'complaint_failed': 'فشل في إرسال الشكوى.',
      'no_complaints_yet': 'ليس لديك أي شكاوى حتى الآن.',
      'faq_q1': 'كيف يمكنني حجز موعد؟',
      'faq_a1': 'يمكنك بسهولة حجز موعد عن طريق اختيار التخصص المطلوب من الصفحة الرئيسية، واختيار طبيبك، وتحديد الوقت المتاح.',
      'faq_q2': 'هل يمكنني إلغاء موعدي؟',
      'faq_a2': 'يمكنك إلغاء المواعيد غير المؤكدة بحرية. ومع ذلك، فإن الإلغاء المتكرر للمواعيد المؤكدة قد يؤدي إلى حظر مؤقت لحسابك.',
      'faq_q3': 'أين يمكنني رؤية نتائجي؟',
      'faq_a3': 'يمكنك الوصول إلى جميع تقاريرك الطبية السابقة وملخصات الذكاء الاصطناعي من علامة التبويب "نتائجي".',
      'faq_q4': 'كيف يتم الدفع؟',
      'faq_a4': 'نقدم خيارات الدفع عبر الإنترنت (البطاقة أو زين كاش) والدفع النقدي في العيادة.',
      'submit_complaint_title': 'اتصل بنا / تقديم شكوى',
      'submit_complaint_sub': 'أرسل مشاكلك إلينا مباشرة.',
      'faqs': 'الأسئلة الشائعة',
      'about_us_label': 'معلومات عنها',
      'about_us_text': 'Tabeebi+ هي منصة صحية حديثة توفر سهولة الوصول إلى الأطباء المتخصصين في جميع أنحاء كركوك. هدفنا هو تسريع عمليات الرعاية الصحية من خلال رقمنة التواصل بين المرضى والأطباء.',
      'complaint_success_msg': 'تم إرسال شكواك بنجاح. سنقوم بمراجعتها والرد عليك في أقرب وقت ممكن.',
      'ai_health_assistant': 'مساعد الصحة الذكي',
      'ai_companion': 'رفيقك الصحي الشخصي. اسأل أي شيء في أي وقت.',
      'ask_ai_btn': 'اسأل الذكاء الاصطناعي',
      'ai_tab': 'ذكاء',
      'ai_chat_title': 'مساعد الصحة الذكي',
      'ai_chat_sub': 'مدعوم من Tabeebi+',
      'ai_empty_title': 'كيف يمكنني مساعدتك؟',
      'ai_empty_sub': 'اسألني عن صحتك أو أعراضك أو أدويتك.',
      'ai_suggestion_1': 'ما هي أعراض الإنفلونزا؟',
      'ai_suggestion_2': 'متى يجب مراجعة الطبيب لصداع الرأس؟',
      'ai_suggestion_3': 'كيف أخفض ضغط الدم بشكل طبيعي؟',
      'ai_input_placeholder': 'اطرح سؤالاً صحياً...',
      'ai_placeholder_response': 'هذا رد تجريبي. تكامل الذكاء الاصطناعي الكامل قادم قريباً!',
    },
    'ku': {
      'home': 'سەرەکی',
      'bookings': 'نۆبەتەکانم',
      'results': 'ئەنجامەکان',
      'alerts': 'ئاگادارییەکان',
      'profile': 'پرۆفایل',
      'loading': 'چاوەڕوانبە',
      'no_available_slots': 'هیچ کاتێکی بەردەستی بۆ ئەمڕۆ نییە.',
      'location_map': 'شوێنی کلینیک',
      'welcome_title': 'پزیشکی متمانەپێکراوت،\nبە یەک کرتەیەک.',
      'welcome_subtitle': 'نۆبەت لەگەڵ پزیشکانی بازاڕی کەرکووک وەربگرە — پزیشکانی پشتڕاستکراو، نرخی ئاشکرا، نۆبەتی هەمان ڕۆژ.',
      'feature_verified': 'پسپۆڕانی پشتڕاستکراو تەنها',
      'feature_private': 'تۆمارەکانت نهێنی دەمێنێتەوە',
      'feature_same_day': 'نۆبەتی هەمان ڕۆژ بەردەستە',
      'btn_start': 'دەست پێبکە',
      'btn_login': 'هەژمارم هەیە',
      'terms_agree': 'بە بەردەوامبوون، ڕازی دەبیت بە مەرجەکان و سیاسەتی نهێنی',
      'login_title': 'چوونە ژوورەوە',
      'login_subtitle': 'چوونە ژوورەوە... کاتەکانی ژوانەکانت.',
      'no_account': 'هەژمارت نییە؟ ',
      'register_link': 'خۆتۆمارکردن',
      'account_not_found': 'هەژمار نەدۆزرایەوە',
      'account_not_found_desc': 'هیچ هەژمارێک بەم ژمارەیە نەدۆزرایەوە. تکایە سەرەتا خۆت تۆمار بکە.',
      'create_account': 'دروستکردنی هەژمار',
      'lets_know_you': 'با ئازات بناسینەوە',
      'register_subtitle': 'ژمارەکەت بۆ دڵنیاکردنەوە و یادکردنەوەی نۆبەتەکانت بەکاردێنین.',
      'full_name': 'ناوی تەواو',
      'name_placeholder': 'نموونە: مستەفا علی',
      'phone_number': 'ژمارەی تەلەفۆن',
      'privacy_notice': 'ژمارەکەت تەنها بۆ دڵنیاکردنەوە و یادکردنەوەی نۆبەتەکان بەکاردێت. هەرگیز بەشداریی ناکەین.',
      'continue_btn': 'بەردەوامبوون',
      'verify_number': 'ژمارەکە دڵنیابکەرەوە',
      'check_messages': 'نامەکانت بپشکنە',
      'otp_subtitle': 'کۆدێکی ٤ ژمارەیی ناردین بۆ',
      'resend_code_in': 'ناردنەوەی کۆد لە ماوەی',
      'resend_code': 'ناردنەوەی کۆد',
      'demo_autofill': 'نوسینی ئۆتۆماتیکی کۆد',
      'verify_continue': 'دڵنیابکەرەوە و بەردەوامبە',
      'good_morning': 'بەیانی باش',
      'good_afternoon': 'ڕۆژ باش',
      'good_evening': 'ئێوارە باش',
      'upcoming_appt': 'نۆبەتی داهاتوو',
      'browse_specialty': 'بگەڕێ بەپێی پسپۆڕی',
      'areas_count': '١٠ بوار',
      'recommended_doctors': 'پزیشکانی پێشنیارکراو بۆ تۆ',
      'recommended_subtitle': 'بەپێی مێژووی نۆبەتەکانت و باشترین پزیشکان',
      'trust_title': 'هەر پزیشکێک پشتڕاستکراوە',
      'trust_sub': 'مۆڵەتەکان هەر سێ مانگێک لەلایەن تیمەکەمانەوە پشکنراودەبێتەوە',
      'my_bookings': 'نۆبەتەکانم',
      'tab_upcoming': 'داهاتووەکان',
      'tab_past': 'ئەوەی تێپەڕیوون',
      'no_appointments': 'هیچ نۆبەتێکی {{tab}} نییە تاکوو ئێستا.',
      'reschedule': 'کاتێکی تری داناین',
      'cancel': 'هەڵوەشاندنەوە',
      'cancel_confirm_title': 'هەڵوەشاندنەوەی نۆبەت',
      'cancel_confirm_message': 'دڵنیایت کە دەتەوێت ئەم نۆبەتە هەڵبوەشێنیتەوە؟',
      'cancel_confirmed_warning': 'ئاگادارکردنەوە: نۆبەتێکی پشتڕاستکراو هەڵدەوەشێنیتەوە. هەڵوەشاندنەوەی زۆر لەوانەیە هەژمارەکەت سنووردار بکات. بەردەوامبوون؟',
      'reschedule_denied_title': 'ناتوانرێت دووبارە کاتێک بدرێتێ',
      'reschedule_denied_message': 'چونکە نۆبەتەکەت پشتڕاستکراوە، دەستکاریی ناتوانیت. تکایە پەیوەندی بە کلینیکەکەوە بکە ئەگەر پێویستە.',
      'view_result': 'بینینی ئەنجام',
      'book_again': 'دووبارە نۆبەت وەرگرە',
      'yes': 'بەڵێ',
      'no': 'نەخێر',
      'ok': 'باشە',
      'book_appointment': 'وەرگرتنی نۆبەت',
      'choose_day': 'ڕۆژێک هەڵبژێرە',
      'available_time': 'کاتی بەردەست',
      'legend_selected': 'هەڵبژێردراو',
      'legend_available': 'بەردەست',
      'legend_unavailable': 'نابەردەست',
      'payment_method': 'شێوازی پارەدان',
      'pay_online': 'پارەدانی ئەلیکترۆنی',
      'pay_online_sub': 'Visa, Mastercard, Zain Cash',
      'instant_confirm': 'پشتڕاستکردنەوەی خێرا',
      'pay_clinic': 'پارەدان لە کلینیکدا',
      'pay_clinic_sub': 'نەقد لە کاتی هاتن · چاوەڕوانی پشتڕاستکردنەوە',
      'summary': 'کورتەبیر',
      'consultation': 'وتووێژ',
      'service_fee': 'کرێی خزمەتگوزاری',
      'total': 'کۆی گشتی',
      'confirm_booking': 'پشتڕاستکردنەوەی نۆبەت',
      'processing': 'جێبەجێدەکرێت...',
      'youre_booked': 'نۆبەتەکەت وەرگیرا!',
      'booking_confirmed_sub': 'پشتڕاستکردنەوەیەکمان ناردە تەلەفۆنەکەت. تکایە ١٠ خولەک زووتر بگەیتە کلینیک.',
      'ticket_date': 'بەروار',
      'ticket_time': 'کات',
      'ticket_location': 'شوێن',
      'ticket_payment': 'پارەدان',
      'paid_online': 'ئەلیکترۆنی پارەدراوە',
      'pay_at_clinic': 'پارەدان لە کلینیکدا',
      'view_my_bookings': 'بینینی نۆبەتەکانم',
      'back_to_home': 'گەڕانەوە بۆ سەرەکی',
      'profile_title': 'پرۆفایل',
      'visits': 'سەردانەکان',
      'your_rating': 'نمرەکەت',
      'my_results': 'ئەنجامەکانم',
      'notifications': 'ئاگادارییەکان',
      'upcoming': 'داهاتوو',
      'reports': 'ڕاپۆرت',
      'unread': 'نەخوێندراوەتەوە',
      'help_center': 'ناوەندی یارمەتی',
      'privacy': 'نهێنی و ئەمنیت',
      'language': 'زمان',
      'english': 'ئینگلیزی',
      'turkish': 'تورکی',
      'arabic': 'عەرەبی',
      'kurdish': 'کوردی',
      'logout': 'چوونەدەرەوە',
      'edit_profile': 'دەستکاریکردنی پرۆفایل',
      'edit_name': 'ناوەکەت',
      'save_changes': 'پاشەکەوتکردنی گۆڕانکارییەکان',
      'updating': 'نوێکردنەوە...',
      'notif_title': 'ئاگادارییەکان',
      'new_alerts': '{{count}} ئاگاداری نوێ',
      'mark_all_read': 'هەمووی وەک خوێندراوەوە نیشانبکە',
      'no_notifications': 'هیچ ئاگادارییەک نییە',
      'no_notifications_sub': 'هیچ نوێکردنەوەیەک یان یادکردنەوەی نۆبەتەکانت نییە.',
      'my_results_title': 'ئەنجامەکانم',
      'results_subtitle': 'تەواوی مێژووی پزیشکیت لە یەک شوێندا',
      'clinical_notes': 'تێبینییە کلینیکییەکان',
      'medications': 'دەرمانەکان',
      'next_steps': 'هەنگاوە داهاتووەکان',
      'all_doctors': 'هەموو پزیشکەکان',
      'available_today': 'بەردەستی ئەمڕۆ',
      'top_rated': 'باشترین نمرە',
      'nearby': 'نزیکەکان',
      'doctors_count': '{{count}} پزیشک',
      'doctor_title': 'پزیشک',
      'experience_suffix': 'ئەزموون',
      'about': 'دەربارەی پزیشک',
      'about_text': 'پسپۆڕ لەگەڵ زیاتر لە {{exp}} کارکردنی کلینیکی. ئەندامی کۆمەڵەی پزیشکانی دەندانی عێراق. تەرکیز لەسەر شێوازە نوێیەکان، کەمکردنەوەی ئێش و پەروەردەی نەخۆش.',
      'working_hours': 'کاتەکانی کار',
      'hours_sat_thu': 'شەممە – پێنج شەممە',
      'hours_fri': 'جومعە',
      'hours_closed': 'داخراو',
      'next_available': 'نزیکترین کاتی بەردەست',
      'see_all': 'هەموویان ببینە',
      'today_badge': 'ئەمڕۆ',
      'consultation_label': 'وتووێژ',
      'book_appointment_btn': 'وەرگرتنی نۆبەت',
      'help_center_title': 'ناوەندی یارمەتی',
      'new_ticket': 'گێلایەکی نوێ',
      'category': 'جۆر',
      'cat_booking': 'نۆبەت',
      'cat_payment': 'پارەدان',
      'cat_results': 'ئەنجامەکان',
      'cat_other': 'ئەمانەی تر',
      'subject_placeholder': 'بابەت',
      'message_placeholder': 'کێشەکەت شیبکرەوە...',
      'submit_ticket': 'ناردنی گێلا',
      'ticket_submitted': '✓ گێلاکە نێردرا',
      'your_tickets': 'گێلاکانت',
      'status_confirmed': 'پشتڕاستکراو',
      'status_pending': 'چاوەڕوانکراو',
      'status_completed': 'تەواوبوو',
      'status_cancelled': 'هەڵوەشاندرایەوە',
      'status_open': 'کراوەیە',
      'status_resolved': 'چارەسەرکرا',
      'privacy_title': 'نهێنی و ئەمنیت',
      'data_protection': 'پاراستنی داتا',
      'data_protection_desc': 'تۆمارە پزیشکییەکانت و داتا کەسیەکانت شفرکراوە و بە شێوەیەکی ئەمن بەپێی ستانداردەکانی تەندروستی پاراستراون.',
      'account_security': 'ئەمنیتی هەژمار',
      'change_phone': 'گۆڕینی ژمارەی تەلەفۆن',
      'delete_account': 'سڕینەوەی هەژمار',
      'delete_warning': 'ئەم کارە بەردەوامە و هەموو مێژووی پزیشکیتی دەسڕێتەوە.',
      'permissions': 'مۆڵەتەکان',
      'notif_perms': 'مۆڵەتەکانی ئاگادارکردنەوە',
      'loc_perms': 'مۆڵەتەکانی شوێن',
      'error': 'هەڵە',
      'rating_save_error': 'نەتوانرا هەڵسەنگاندنەکە پاشەکەوت بکرێت: ',
      'thanks': 'سوپاس',
      'rating_success': 'هەڵسەنگاندنەکەت بە سەرکەوتوویی نێردرا!',
      'something_went_wrong': 'کێشەیەک ڕوویدا: ',
      'unknown_doctor': 'پزیشکی نەناسراو',
      'rate_doctor_title': 'هەڵسەنگاندنی پزیشک',
      'rate_doctor_sub': 'چاوپێکەوتنەکەت لەگەڵ {{doctor}} هەڵسەنگێنە.',
      'rate_doctor_placeholder': 'لێدوانەکانت سەبارەت بە پزیشک و پشکنینەکە بنووسە (ئارەزوومەندانە)...',
      'cancel_btn_text': 'پاشگەزبوونەوە',
      'submit_btn_text': 'ناردن',
      'saving': 'پاشەکەوت دەکرێت...',
      'rated_x_out_of_5': '⭐ هەڵسەنگێندراوە بە {{rating}} / 5',
      'rate_btn': '⭐ هەڵسەنگاندن',
      'day_mon': 'دووشەممە',
      'day_tue': 'سێشەممە',
      'day_wed': 'چوارشەممە',
      'day_thu': 'پێنجشەممە',
      'day_fri': 'هەینی',
      'day_sat': 'شەممە',
      'day_sun': 'یەکشەممە',
      'view_on_maps': 'پیشاندان لە نەخشەی گۆگڵ',
      'no_location_info': 'زانیاری شوێن بەردەست نییە.',
      'reports_available': '{{count}} ڕاپۆرت بەردەستە',
      'no_reports_yet': 'تا ئێستا هیچ ڕاپۆرتێک بارنەکراوە.',
      'ai_summary': 'پوختەی زیرەکی دەستکرد',
      'summary_not_ready': 'پوختەکە هێشتا دروست نەکراوە.',
      'view_report_pdf': 'بینینی ڕاپۆرت (PDF)',
      'downloading': 'دادەبەزێت...',
      'sharing_not_available': 'هاوبەشکردن لەم ئامێرەدا بەردەست نییە.',
      'pdf_download_error': 'نەتوانرا PDF دابەزێنرێت. تکایە دووبارە هەوڵ بدەوە.',
      'no_report_available': 'پشکنینی پزیشکی ئەنجامدرا. هیچ ڕاپۆرتێک بەردەست نییە.',
      'complaint_failed': 'ناردنی سکاڵاکە سەرکەوتوو نەبوو.',
      'no_complaints_yet': 'تا ئێستا هیچ سکاڵایەکت نییە.',
      'faq_q1': 'چۆن دەتوانم چاوپێکەوتنێک دیاری بکەم؟',
      'faq_a1': 'دەتوانیت بە ئاسانی چاوپێکەوتنێک دیاری بکەیت بە هەڵبژاردنی پسپۆڕیی مەبەست لە پەڕەی سەرەکی، هەڵبژاردنی پزیشکەکەت، و دیاریکردنی کاتێکی گونجاو.',
      'faq_q2': 'ئایا دەتوانم چاوپێکەوتنەکەم هەڵبوەشێنمەوە؟',
      'faq_a2': 'دەتوانیت بە ئازادی چاوپێکەوتنە پەسەندنەکراوەکان هەڵبوەشێنیتەوە. بەڵام هەڵوەشاندنەوەی زۆری چاوپێکەوتنە پەسەندکراوەکان لەوانەیە ببێتە هۆی بلۆککردنی کاتی هەژمارەکەت.',
      'faq_q3': 'لە کوێ دەتوانم ئەنجامەکانم ببینم؟',
      'faq_a3': 'دەتوانیت دەستت بگات بە هەموو ڕاپۆرتە پزیشکییەکانی ڕابردووت و پوختەکانی زیرەکی دەستکرد لە تابی "ئەنجامەکانم".',
      'faq_q4': 'پارەدان چۆن دەکرێت؟',
      'faq_a4': 'هەردوو هەڵبژاردەی پارەدانی سەرهێڵ (کارت یان زەین کاش) و پارەدانی نەختینەیی لە نۆرینگەدا بەردەستن.',
      'submit_complaint_title': 'پەیوەندیمان پێوە بکە / سکاڵا پێشکەش بکە',
      'submit_complaint_sub': 'کێشەکانت ڕاستەوخۆ بنێرە بۆ ئێمە.',
      'faqs': 'پرسیارە باوەکان',
      'about_us_label': 'دەربارەی ئێمە',
      'about_us_text': 'Tabeebi+ سەکۆیەکی تەندروستیی مۆدێرنە کە گەیشتن بە پزیشکە پسپۆڕەکان لە سەرتاسەری کەرکوک ئاسان دەکات. ئامانجمان خێراکردنی پڕۆسەکانی چاودێری تەندروستییە لە ڕێگەی بەدیجیتاڵکردنی پەیوەندی نێوان نەخۆش و پزیشک.',
      'complaint_success_msg': 'سکاڵاکەت بە سەرکەوتوویی نێردرا. پێداچوونەوەی بۆ دەکەین و بە زووترین کات وەڵامت دەدەینەوە.',
      'ai_health_assistant': 'يارمەتیدەری تەندروستی AI',
      'ai_companion': 'هاوەڵی تەندروستی تایبەتی تۆ. هەرکاتێک بێت بپرسە.',
      'ask_ai_btn': 'لە زیرەکی دەستکرد بپرسە',
      'ai_tab': 'AI',
      'ai_chat_title': 'يارمەتیدەری تەندروستی AI',
      'ai_chat_sub': 'بە هێزەی Tabeebi+',
      'ai_empty_title': 'چۆن دەتوانم یارمەتتبێتم؟',
      'ai_empty_sub': 'دەتوانیت لەبارەی تەندروستیتەوە هەر پرسیارێک بکەیت.',
      'ai_suggestion_1': 'نیشانەکانی ئنفلوۙونزا چیین؟',
      'ai_suggestion_2': 'کەکەی بەردەوستی بۆنی بۆکانەوە داکتۆر ببینم؟',
      'ai_suggestion_3': 'چۆن بە شێوازی سڕوشت کەینی خەوی خۆین دەخەم؟',
      'ai_input_placeholder': 'پرسیارێکی تەندروستیی بکە...',
      'ai_placeholder_response': 'ئەمە وەڵامێکی دەستەبێرە. یەکسودەیی AI بە زووترین کاتێک دێتێ!',
    },
  };

  static String t(String key, [Map<String, dynamic>? params]) {
    final lang = currentLanguage;
    final dict = _translations[lang] ?? _translations['en']!;
    var val = dict[key] ?? _translations['en']?[key] ?? key;
    
    if (params != null && params.isNotEmpty) {
      params.forEach((k, v) {
        val = val.replaceAll('{{$k}}', v.toString());
      });
    }
    return val;
  }

  static bool get isRtl {
    return currentLanguage == 'ar' || currentLanguage == 'ku';
  }
}
